apiVersion: apps/v1
kind: Deployment
  
metadata:
  name: passin-deployment
  labels:
    app: passin

spec:
  replicas: 5
  selector:
    matchLabels:
      app: passin
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers: 
        - name: passin
          image: damasc84/passin-backend:2069417
          env:
            - name: DB_HOST
              value: "terraform-20240426152716456200000001.cnmgy8a06r5x.us-east-1.rds.amazonaws.com"
            - name: DB_NAME
              value: "passin"
            - name: DB_SA_PASSWORD
              value: "reallyStrongPwd123"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 512Mi