apiVersion: apps/v1
kind: Deployment
  
metadata:
  name: passin-deployment
  labels:
    app: passin

spec:
  replicas: 3
  selector:
    matchLabels:
      app: passin
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers: 
        - name: passin
          image: damasc84/passin-backend:bff6d34
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: url
            - name: DB_NAME
              value: "passin"
            - name: DB_SA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: passin-env
                  key: sa_password
            - name: DOTNET_RUNNING_IN_CONTAINER
              value: "true"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1024Mi"
              cpu: "600m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"