apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: passin-eks
  region: us-east-1
  
vpc:
  id: "vpc-045d2e7d2abb3a2fa"
  subnets:
    public:
      us-east-1a:
        id: "subnet-021afedef752aff0a"
      us-east-1b:
        id: "subnet-06968e348201daba3"
      us-east-1c:
        id: "subnet-0bf8dda53fa9b3292"
      us-east-1d:
        id: "subnet-0f15970fb928f9be7"
      us-east-1f:
        id: "subnet-09eea340ec58c2d89"

nodeGroups:
  - name: node-1
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    iam:
      instanceRoleARN: arn:aws:iam::533267083060:role/EKSWorkerNode
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs:
        - "sg-0c29a922e245f6724"  # Cluster security group
        - "sg-0d7eefab879c2a856"  # Additional security group

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

iam:
  serviceRoleARN: arn:aws:iam::533267083060:role/EKSClusterRole